
id: ea66d776-3936-48b5-8e10-cdc550e616d7
name: Disabled soft- or hard match of Microsoft Entra Connect sync
description: |
  'Change of sync configuration to overwrite and take-over (Entra ID) cloud-only accounts from Microsoft Entra Connect server (on-premises)'
severity: Medium
requiredDataConnectors:
  - connectorId: AzureActiveDirectory
    dataTypes:
      - AuditLogs
queryFrequency: 30m
queryPeriod: 1h
triggerOperator: gt
triggerThreshold: 0
tactics:
  - Persistence
  - CredentialAccess
  - PrivilegeEscalation
  - InitialAccess
relevantTechniques:
  - T1136
  - T1098
  - T1078
query: |
  AuditLogs
  | where ingestion_time() > ago(40m)
  | where OperationName has "Set DirSync feature"
  | where Category has "DirectoryManagement"
  | where parse_json(tostring(TargetResources[0].modifiedProperties))[0].displayName == "DirSyncFeatures"
  | extend NewValue = parse_json(tostring(parse_json(tostring(TargetResources[0].modifiedProperties))[0].newValue))[0]
  | extend OldValue = parse_json(tostring(parse_json(tostring(TargetResources[0].modifiedProperties))[0].oldValue))[0]
  | extend UserPrincipalName =  parse_json(tostring(InitiatedBy.user)).userPrincipalName
  | extend IPAddress =  parse_json(tostring(InitiatedBy.user)).ipAddress
  | extend timestamp = TimeGenerated, IPCustomEntity = IPAddress, AccountCustomEntity = UserPrincipalName
entityMappings:
  - entityType: Account
    fieldMappings:
      - identifier: FullName
        columnName: AccountCustomEntity
  - entityType: IP
    fieldMappings:
      - identifier: Address
        columnName: IPAddress
version: 1.0.2
kind: Scheduled